name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check syntax
        run: |
          source git-bash-aliases.bash
      - name: Build Debian package
        run: |
          make dist
